services:
  marketplace-api:
    image: ${DOCKER_REGISTRY-}marketplaceapi
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8080:8080"
    volumes:
      - ./Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ./frontend/public/uploads:/app/public/uploads
    container_name: marketplace-api
    networks:
      - market
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: YourStrongPassword123!
      POSTGRES_DB: marketplace
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    container_name: postgres-db
    networks:
      - market

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    container_name: my-redis-container
    networks:
      - market
    ports:
      - "6379:6379"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: marketplace-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/public/uploads:/app/public/uploads
    networks:
      - market
    depends_on:
      - marketplace-api

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - marketplace-api
    networks:
      - market

networks:
  market:
    driver: bridge

volumes:
  db_data:
  redis_data:
